### ISSUE TITLE
Issue with release binaries

### ISSUE THREAD

**Issue by jmvezic** [pwinckles/rocfl#4]
When using the unzipped released Linux binary, running

```
./rocfl --help
```

I get:

```
-bash: ./rocfl: Permission denied
```

Using sudo with the same command I get:
```
sudo: ./rocfl: command not found
```

**Comment by pwinckles** [comment]
@jmvezic you need to change the permissions on the binary. For example:

```shell
chmod 755 rocfl
```

I'll look into getting the build process updated to bundle them with the correct permissions by default.

**Comment by pwinckles** [comment]
Unfortunately, the permission loss is a Github bug that does not currently have a great solution: https://github.com/actions/upload-artifact/issues/38

**Comment by jmvezic** [comment]
That works, thanks for the solution!
