### ISSUE TITLE
Profile option for S3 connection

### ISSUE THREAD

**Issue by ives1227** [pwinckles/rocfl#5]
This tool is great for its interactions when I use it locally.  However, I have some data stored in S3 and the tool doesn't seem to allow for a way to connect to S3 via the use of profiles.

For example: `aws s3 ls s3://mybucketname --profile abc ` lists the contents of the bucket called 'mybucketname' when using the credentials listed under profile 'abc'.

I would like to be able to do something like this:
`rocfl -b mybucketname ls --profile abc `

**Comment by pwinckles** [comment]
@ives1227 Thanks for the ticket. I can definitely add this. I'll both add a flag and expose a new variable you could add to the [config file](https://github.com/pwinckles/rocfl#configuration).

**Comment by ives1227** [comment]
@pwinckles terrific - thanks so much!

**Comment by pwinckles** [comment]
@ives1227 Are you able to, or have any interest in, building this PR locally and verifying that it behaves as you expected?

**Comment by ives1227** [comment]
@pwinckles - I did test it and left comments in the PR: https://github.com/pwinckles/rocfl/pull/6#issuecomment-880357986. Thanks!

**Comment by pwinckles** [comment]
@ives1227 I believe this issue should be resolved. Feel free to open other tickets if you'd like help sorting out the errors you described in the PR -- they sound like configuration problems.
